import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboadWrapper from "./DashboardWrapper";

const inter = localFont({
  src: "./fonts/Inter-Regular.woff",
  variable: "--font-inter",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <DashboadWrapper>{children}</DashboadWrapper>
      </body>
    </html>
  );
}
